import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Snowfall } from "@/components/Snowfall";
import { ChristmasLights } from "@/components/ChristmasLights";
import { Chatbot } from "@/components/Chatbot";
import "./globals.css";
const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://boo-shop.vercel.app";
export const metadata:Metadata={metadataBase:new URL(siteUrl),title:{default:"BOO SHOP — Noël & Halloween",template:"%s · BOO SHOP"},description:"Collections BOO de personnages sensoriels : Noël, Spooky, Monster, Mystery et Neon Glow.",robots:{index:true,follow:true}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="fr"><body className="min-h-screen bg-[#071210] font-sans antialiased text-white"><ChristmasLights/><Snowfall/><div className="relative z-10 min-h-screen"><div className="border-b border-amber-200/10 bg-[#0b2119]/90 px-4 py-2 text-center text-xs text-white/70">🎄 NOËL CHEZ BOO · NOUVELLE COLLECTION EN PRÉPARATION</div><Header/><div className="min-h-[60vh]">{children}</div><footer className="border-t border-white/8 bg-[#050d0b]"><div className="container grid gap-8 py-12 sm:grid-cols-3 text-sm"><div><p className="font-display text-xl tracking-[.18em]">BOO<span className="text-red-400">·</span>SHOP</p><p className="mt-3 text-white/45">Plus qu'une collection, une émotion.</p></div><div><p className="mb-3 font-medium">Collections</p><Link className="block text-white/45 hover:text-white" href="/personnages#noel">🎄 Noël</Link><Link className="block text-white/45 hover:text-white" href="/personnages#halloween">🎃 Halloween</Link><Link className="block text-white/45 hover:text-white" href="/personnages">Tous les personnages</Link></div><div><p className="mb-3 font-medium">Aide</p><Link className="block text-white/45 hover:text-white" href="/liste-de-souhaits">♡ Liste de souhaits</Link><Link className="block text-white/45 hover:text-white" href="/contact">Contact</Link><Link className="block text-white/45 hover:text-white" href="/cart">Panier</Link></div></div><div className="border-t border-white/8 py-5 text-center text-xs text-white/35">© {new Date().getFullYear()} BOO SHOP</div></footer></div><Chatbot/></body></html>}