export type CollectionSlug = "christmas" | "spooky" | "monster" | "mystery" | "neon";

export type BooCharacter = {
  id: string;
  name: string;
  collection: CollectionSlug;
  collectionLabel: string;
  symbol: string;
  accent: string;
  secondary: string;
  isNew: boolean;
  tagline: string;
};

export const COLLECTIONS = [
  { slug: "christmas", label: "Collection Noël", emoji: "🎄", description: "24 personnages festifs conçus comme une famille BOO exclusive.", tone: "noël" },
  { slug: "spooky", label: "Collection Spooky", emoji: "🎃", description: "Les classiques Halloween revisités dans l'univers BOO.", tone: "halloween" },
  { slug: "monster", label: "Collection Monster", emoji: "👾", description: "Des monstres colorés, expressifs et collectionnables.", tone: "halloween" },
  { slug: "mystery", label: "Collection Mystery", emoji: "❓", description: "Des personnages mystérieux à découvrir surprise après surprise.", tone: "halloween" },
  { slug: "neon", label: "Collection Neon Glow", emoji: "✨", description: "Des créatures fluos pensées pour un effet lumineux spectaculaire.", tone: "halloween" },
 ] as const;

const christmasBase = [
  ["Père Noël", "🎅"],
  ["Mère Noël", "🤶"],
  ["Rudolph", "🦌"],
  ["Elfe", "🧝"],
  ["Bonhomme de neige", "⛄"],
  ["Pingouin de Noël", "🐧"],
  ["Ours polaire", "🐻‍❄️"],
  ["Manchot", "🐧"],
  ["Cadeau", "🎁"],
  ["Sapin", "🎄"],
  ["Boule de Noël", "🔴"],
  ["Cloche", "🔔"],
  ["Lutin", "🧝"],
  ["Renard de Noël", "🦊"],
  ["Gingerbread", "🍪"],
  ["Étoile de Noël", "⭐"],
  ["Chocolat chaud", "☕"],
  ["Canne à sucre", "🍭"],
  ["Flocon", "❄️"],
  ["Couronne", "👑"],
  ["Bougie", "🕯️"],
  ["Casse-noisette", "🪖"],
  ["Roi des neiges", "👑"],
  ["Gnome de Noël", "🎄"],
] as const;

const halloweenSource = {
  spooky: [
    ["Fantôme Boo", "👻", false],
    ["Citrouille Sourire", "🎃", false],
    ["Chat Nuit", "🐈‍⬛", false],
    ["Chat Violet", "🐈", false],
    ["Spectre Vert", "👻", false],
    ["Crâne", "💀", false],
    ["Poulpe Orange", "🐙", false],
    ["Blob Violet", "🟣", false],
    ["Fantôme Brume", "👻", true],
    ["Citrouille Noire", "🎃", true],
    ["Sorcière Pop", "🧙", true],
    ["Vampire Mini", "🧛", true],
    ["Diable Rouge", "😈", true],
    ["Araignée Plush", "🕷️", true],
    ["Chauve-souris", "🦇", true],
    ["Loup-garou", "🐺", true],
    ["Momie", "🧟", true],
    ["Zombie", "🧟‍♂️", true],
    ["Faucheuse", "☠️", true],
    ["Clown Creepy", "🤡", true],
    ["Corbeau", "🐦‍⬛", true],
    ["Hibou Sorcier", "🦉", true],
    ["Jack-O", "🎃", true],
    ["Fantomette", "👻", true],
  ],
  monster: [
    ["Cyclope Bleu", "👁️", false],
    ["Monstre Vert", "👹", false],
    ["Monstre Violet", "👾", false],
    ["Monstre Rose", "🩷", false],
    ["Monstre Jaune", "🟡", false],
    ["Monstre Orange", "🟠", false],
    ["Blob Turquoise", "🔵", false],
    ["Monstre Nuit", "🟣", false],
    ["Mini Cyclope", "👁️", true],
    ["Blob Lime", "🟢", true],
    ["Cornu Bleu", "👹", true],
    ["Draco Monstre", "🐲", true],
    ["Yéti Pop", "👹", true],
    ["Raptor", "🦖", true],
    ["Gorille Glow", "🦍", true],
    ["Crabe Monstre", "🦀", true],
    ["Crocodile Pop", "🐊", true],
    ["Robot Monstre", "🤖", true],
    ["Alien", "👽", true],
    ["Poilu Rose", "🩷", true],
    ["Tentacule", "🐙", true],
    ["Chimère", "🦁", true],
    ["Roche Vivante", "🪨", true],
    ["Bébé Monstre", "👾", true],
  ],
  mystery: [
    ["Cœur Rose", "💗", false],
    ["Nuage Bleu", "☁️", false],
    ["Bulle Rose", "🫧", false],
    ["Planète", "🪐", false],
    ["Blob Vert", "🟢", false],
    ["Cube Mystère", "🟪", false],
    ["Étoile Jaune", "⭐", false],
    ["Blob Orange", "🟠", false],
    ["Coffre Surprise", "📦", true],
    ["Lapin Secret", "🐰", true],
    ["Chat Mystère", "🐱", true],
    ["Licorne", "🦄", true],
    ["Dragon Secret", "🐲", true],
    ["Panda Secret", "🐼", true],
    ["Hérisson", "🦔", true],
    ["Tortue", "🐢", true],
    ["Axolotl", "🦎", true],
    ["Baleine", "🐋", true],
    ["Dino Secret", "🦖", true],
    ["Méduse", "🪼", true],
    ["Crabe", "🦀", true],
    ["Poulpe", "🐙", true],
    ["Château", "🏰", true],
    ["Roue Vortex", "🌀", true],
  ],
  neon: [
    ["Étoile Glow", "⭐", false],
    ["Fantôme Bleu", "👻", false],
    ["Sourire Rose", "😊", false],
    ["Ananas Fluo", "🍍", false],
    ["Chat Violet Glow", "🐈", false],
    ["Alien Vert", "👽", false],
    ["Balle Spiky", "🔵", false],
    ["Champignon Rose", "🍄", false],
    ["Lune Glow", "🌙", true],
    ["Cœur Neon", "💖", true],
    ["Soleil Fluo", "☀️", true],
    ["Cristal", "💎", true],
    ["Arc-en-ciel", "🌈", true],
    ["Fleur Laser", "🌸", true],
    ["Cactus Glow", "🌵", true],
    ["Aqua Glow", "💧", true],
    ["Iris Neon", "🌺", true],
    ["Dragon Glow", "🐉", true],
    ["Licorne Glow", "🦄", true],
    ["Papillon Glow", "🦋", true],
    ["Requin Glow", "🦈", true],
    ["Pieuvre Glow", "🐙", true],
    ["Méduses Glow", "🪼", true],
    ["Astro", "🌌", true],
  ],
} as const;

const tones: Record<CollectionSlug, [string,string]> = {
  christmas: ["#d71920", "#1f6b45"],
  spooky: ["#f97316", "#8b5cf6"],
  monster: ["#84cc16", "#22d3ee"],
  mystery: ["#d946ef", "#22d3ee"],
  neon: ["#22d3ee", "#d946ef"],
};

const collectionLabels: Record<CollectionSlug, string> = { christmas: "Collection Noël", spooky: "Collection Spooky", monster: "Collection Monster", mystery: "Collection Mystery", neon: "Collection Neon Glow" };

const taglines: Record<CollectionSlug, string> = { christmas: "La magie de Noël façon BOO.", spooky: "Des frissons tout doux.", monster: "Des monstres à collectionner.", mystery: "Quel personnage vas-tu découvrir ?", neon: "Glow, couleur et bonne humeur." };

export const BOO_CHARACTERS: BooCharacter[] = [
  { id: "christmas-01", name: "Père Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🎅", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-02", name: "Mère Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🤶", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-03", name: "Rudolph", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🦌", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-04", name: "Elfe", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🧝", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-05", name: "Bonhomme de neige", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "⛄", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-06", name: "Pingouin de Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🐧", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-07", name: "Ours polaire", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🐻‍❄️", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-08", name: "Manchot", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🐧", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-09", name: "Cadeau", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🎁", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-10", name: "Sapin", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🎄", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-11", name: "Boule de Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🔴", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-12", name: "Cloche", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🔔", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-13", name: "Lutin", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🧝", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-14", name: "Renard de Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🦊", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-15", name: "Gingerbread", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🍪", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-16", name: "Étoile de Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "⭐", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-17", name: "Chocolat chaud", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "☕", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-18", name: "Canne à sucre", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🍭", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-19", name: "Flocon", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "❄️", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-20", name: "Couronne", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "👑", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-21", name: "Bougie", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🕯️", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-22", name: "Casse-noisette", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🪖", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-23", name: "Roi des neiges", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "👑", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "christmas-24", name: "Gnome de Noël", collection: "christmas", collectionLabel: collectionLabels.christmas, symbol: "🎄", accent: "#d71920", secondary: "#1f6b45", isNew: true, tagline: taglines.christmas },
  { id: "spooky-01", name: "Fantôme Boo", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "👻", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-02", name: "Citrouille Sourire", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🎃", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-03", name: "Chat Nuit", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🐈‍⬛", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-04", name: "Chat Violet", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🐈", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-05", name: "Spectre Vert", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "👻", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-06", name: "Crâne", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "💀", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-07", name: "Poulpe Orange", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🐙", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-08", name: "Blob Violet", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🟣", accent: "#f97316", secondary: "#8b5cf6", isNew: false, tagline: taglines["spooky"] },
  { id: "spooky-09", name: "Fantôme Brume", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "👻", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-10", name: "Citrouille Noire", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🎃", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-11", name: "Sorcière Pop", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🧙", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-12", name: "Vampire Mini", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🧛", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-13", name: "Diable Rouge", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "😈", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-14", name: "Araignée Plush", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🕷️", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-15", name: "Chauve-souris", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🦇", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-16", name: "Loup-garou", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🐺", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-17", name: "Momie", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🧟", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-18", name: "Zombie", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🧟‍♂️", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-19", name: "Faucheuse", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "☠️", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-20", name: "Clown Creepy", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🤡", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-21", name: "Corbeau", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🐦‍⬛", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-22", name: "Hibou Sorcier", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🦉", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-23", name: "Jack-O", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "🎃", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "spooky-24", name: "Fantomette", collection: "spooky", collectionLabel: collectionLabels[""+slug], symbol: "👻", accent: "#f97316", secondary: "#8b5cf6", isNew: true, tagline: taglines["spooky"] },
  { id: "monster-01", name: "Cyclope Bleu", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👁️", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-02", name: "Monstre Vert", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👹", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-03", name: "Monstre Violet", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👾", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-04", name: "Monstre Rose", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🩷", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-05", name: "Monstre Jaune", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🟡", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-06", name: "Monstre Orange", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🟠", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-07", name: "Blob Turquoise", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🔵", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-08", name: "Monstre Nuit", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🟣", accent: "#84cc16", secondary: "#22d3ee", isNew: false, tagline: taglines["monster"] },
  { id: "monster-09", name: "Mini Cyclope", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👁️", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-10", name: "Blob Lime", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🟢", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-11", name: "Cornu Bleu", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👹", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-12", name: "Draco Monstre", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🐲", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-13", name: "Yéti Pop", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👹", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-14", name: "Raptor", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🦖", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-15", name: "Gorille Glow", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🦍", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-16", name: "Crabe Monstre", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🦀", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-17", name: "Crocodile Pop", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🐊", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-18", name: "Robot Monstre", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🤖", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-19", name: "Alien", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👽", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-20", name: "Poilu Rose", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🩷", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-21", name: "Tentacule", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🐙", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-22", name: "Chimère", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🦁", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-23", name: "Roche Vivante", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "🪨", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "monster-24", name: "Bébé Monstre", collection: "monster", collectionLabel: collectionLabels[""+slug], symbol: "👾", accent: "#84cc16", secondary: "#22d3ee", isNew: true, tagline: taglines["monster"] },
  { id: "mystery-01", name: "Cœur Rose", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "💗", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-02", name: "Nuage Bleu", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "☁️", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-03", name: "Bulle Rose", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🫧", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-04", name: "Planète", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🪐", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-05", name: "Blob Vert", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🟢", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-06", name: "Cube Mystère", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🟪", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-07", name: "Étoile Jaune", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "⭐", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-08", name: "Blob Orange", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🟠", accent: "#d946ef", secondary: "#22d3ee", isNew: false, tagline: taglines["mystery"] },
  { id: "mystery-09", name: "Coffre Surprise", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "📦", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-10", name: "Lapin Secret", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐰", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-11", name: "Chat Mystère", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐱", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-12", name: "Licorne", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🦄", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-13", name: "Dragon Secret", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐲", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-14", name: "Panda Secret", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐼", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-15", name: "Hérisson", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🦔", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-16", name: "Tortue", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐢", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-17", name: "Axolotl", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🦎", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-18", name: "Baleine", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐋", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-19", name: "Dino Secret", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🦖", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-20", name: "Méduse", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🪼", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-21", name: "Crabe", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🦀", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-22", name: "Poulpe", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🐙", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-23", name: "Château", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🏰", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "mystery-24", name: "Roue Vortex", collection: "mystery", collectionLabel: collectionLabels[""+slug], symbol: "🌀", accent: "#d946ef", secondary: "#22d3ee", isNew: true, tagline: taglines["mystery"] },
  { id: "neon-01", name: "Étoile Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "⭐", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-02", name: "Fantôme Bleu", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "👻", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-03", name: "Sourire Rose", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "😊", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-04", name: "Ananas Fluo", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🍍", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-05", name: "Chat Violet Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🐈", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-06", name: "Alien Vert", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "👽", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-07", name: "Balle Spiky", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🔵", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-08", name: "Champignon Rose", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🍄", accent: "#22d3ee", secondary: "#d946ef", isNew: false, tagline: taglines["neon"] },
  { id: "neon-09", name: "Lune Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌙", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-10", name: "Cœur Neon", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "💖", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-11", name: "Soleil Fluo", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "☀️", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-12", name: "Cristal", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "💎", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-13", name: "Arc-en-ciel", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌈", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-14", name: "Fleur Laser", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌸", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-15", name: "Cactus Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌵", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-16", name: "Aqua Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "💧", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-17", name: "Iris Neon", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌺", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-18", name: "Dragon Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🐉", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-19", name: "Licorne Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🦄", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-20", name: "Papillon Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🦋", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-21", name: "Requin Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🦈", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-22", name: "Pieuvre Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🐙", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-23", name: "Méduses Glow", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🪼", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
  { id: "neon-24", name: "Astro", collection: "neon", collectionLabel: collectionLabels[""+slug], symbol: "🌌", accent: "#22d3ee", secondary: "#d946ef", isNew: true, tagline: taglines["neon"] },
];

export const CHRISTMAS_CHARACTERS = BOO_CHARACTERS.filter((c) => c.collection === "christmas");
export const HALLOWEEN_BASE_CHARACTERS = BOO_CHARACTERS.filter((c) => c.collection !== "christmas" && !c.isNew);
export const HALLOWEEN_NEW_CHARACTERS = BOO_CHARACTERS.filter((c) => c.collection !== "christmas" && c.isNew);

export function getCharacter(id: string) { return BOO_CHARACTERS.find((c) => c.id === id); }

export function getCollection(slug: CollectionSlug) { return COLLECTIONS.find((c) => c.slug === slug); }
